-- 코드를 입력하세요
WITH MILK AS (
    SELECT CART_ID
    FROM CART_PRODUCTS
    WHERE NAME = 'Milk'
), 
YOGURT AS (
    SELECT CART_ID
    FROM CART_PRODUCTS
    WHERE NAME = 'Yogurt'
)

SELECT DISTINCT CART_ID
FROM CART_PRODUCTS
WHERE CART_ID IN (SELECT CART_ID FROM MILK) AND CART_ID IN (SELECT CART_ID FROM YOGURT)
ORDER BY CART_ID