-- 코드를 작성해주세요
WITH TEMP AS (
    SELECT PARENT_ID AS ID, COUNT(*) AS COUNT
    FROM ECOLI_DATA 
    GROUP BY PARENT_ID
)

SELECT D.ID,
    CASE
        WHEN T.COUNT IS NULL THEN 0
        ELSE T.COUNT
    END AS CHILD_COUNT
FROM ECOLI_DATA D
LEFT JOIN TEMP T ON D.ID = T.ID
ORDER BY D.ID