-- 코드를 입력하세요
WITH TEMP1 AS (
    SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
    FROM ONLINE_SALE
    WHERE YEAR(SALES_DATE) = 2022 AND MONTH(SALES_DATE) = 3
),
TEMP2 AS (
    SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE, PRODUCT_ID, NULL AS USER_ID, SALES_AMOUNT
    FROM OFFLINE_SALE
    WHERE YEAR(SALES_DATE) = 2022 AND MONTH(SALES_DATE) = 3
)

SELECT SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT FROM TEMP1
UNION
SELECT SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT FROM TEMP2
ORDER BY SALES_DATE, PRODUCT_ID, USER_ID