-- 코드를 입력하세요
WITH RENTING AS (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
    WHERE START_DATE <= '2022-11-30' AND '2022-11-01' <= END_DATE
),
DAY_30 AS (
    SELECT CAR_TYPE, DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN 
    WHERE DURATION_TYPE = '30일 이상'
),
TEMP AS (
    SELECT C.CAR_ID, C.CAR_TYPE, ROUND(30 * C.DAILY_FEE * ((100 - D.DISCOUNT_RATE) / 100)) AS FEE
    FROM CAR_RENTAL_COMPANY_CAR C
    JOIN DAY_30 D ON C.CAR_TYPE = D.CAR_TYPE
)

SELECT CAR_ID, CAR_TYPE, FEE
FROM TEMP
WHERE CAR_TYPE IN ('세단', 'SUV') AND CAR_ID NOT IN (SELECT CAR_ID FROM RENTING) AND 500000 <= FEE AND FEE < 2000000
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC