-- 코드를 입력하세요
WITH BUSY AS (
    SELECT DISTINCT CAR_ID AS CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
    WHERE (DATE_FORMAT(START_DATE, '%Y-%m-%d') BETWEEN '2022-11-01' AND '2022-11-30') OR
        (DATE_FORMAT(END_DATE, '%Y-%m-%d') BETWEEN '2022-11-01' AND '2022-11-30') OR
        (DATE_FORMAT(START_DATE, '%Y-%m-%d') < '2022-11-01' AND DATE_FORMAT(END_DATE, '%Y-%m-%d') > '2022-11-30')
),
TEMP AS (
    SELECT CAR_TYPE, REPLACE(DISCOUNT_RATE, '%', '%') AS DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN 
    WHERE CAR_TYPE IN ('세단', 'SUV') AND DURATION_TYPE LIKE "30%"
)

SELECT C.CAR_ID, C.CAR_TYPE, 30 * C.DAILY_FEE * (100 - T.DISCOUNT_RATE) / 100 AS FEE
FROM CAR_RENTAL_COMPANY_CAR C
JOIN TEMP T ON C.CAR_TYPE = T.CAR_TYPE
WHERE C.CAR_TYPE IN ('세단', 'SUV') AND 
        C.CAR_ID NOT IN (SELECT CAR_ID FROM BUSY) AND 
        30 * C.DAILY_FEE * (100 - T.DISCOUNT_RATE) / 100 >= 500000 AND
        30 * C.DAILY_FEE * (100 - T.DISCOUNT_RATE) / 100 < 2000000
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC