-- 코드를 입력하세요
WITH TEMP AS (
    SELECT WRITER_ID
    FROM USED_GOODS_BOARD 
    GROUP BY WRITER_ID
    HAVING COUNT(*) >= 3
)

SELECT USER_ID, NICKNAME, 
    CONCAT(CITY, ' ', STREET_ADDRESS1, ' ', STREET_ADDRESS2) AS 전체주소,
    CONCAT(MID(TLNO, 1, 3), '-', MID(TLNO, 4, 4), '-', MID(TLNO, 8, 4)) AS 전화번호
FROM USED_GOODS_USER 
WHERE USER_ID IN (SELECT WRITER_ID FROM TEMP)
ORDER BY USER_ID DESC