-- 코드를 입력하세요
WITH TEMP AS (
    SELECT REST_ID
    FROM REST_INFO
    WHERE ADDRESS LIKE '서울%'
)

SELECT I.REST_ID, I.REST_NAME, I.FOOD_TYPE, I.FAVORITES, I.ADDRESS, ROUND(AVG(R.REVIEW_SCORE), 2) AS SCORE
FROM REST_INFO I
JOIN REST_REVIEW R ON I.REST_ID = R.REST_ID
WHERE I.REST_ID IN (SELECT REST_ID FROM TEMP)
GROUP BY I.REST_ID
ORDER BY SCORE DESC, FAVORITES DESC