-- 코드를 입력하세요
WITH TEMP AS (
    SELECT COUNT(*) AS TOTAL
    FROM USER_INFO
    WHERE YEAR(JOINED) = 2021
)

SELECT YEAR(S.SALES_DATE) AS YEAR, MONTH(S.SALES_DATE) AS MONTH, COUNT(DISTINCT I.USER_ID) AS PURCHASED_USERS,
    ROUND(COUNT(DISTINCT I.USER_ID) / (SELECT TOTAL FROM TEMP), 1) AS PUCHASED_RATIO
FROM USER_INFO I
JOIN ONLINE_SALE S ON I.USER_ID = S.USER_ID
WHERE YEAR(I.JOINED) = 2021
GROUP BY YEAR(S.SALES_DATE), MONTH(S.SALES_DATE)
ORDER BY YEAR, MONTH