-- 코드를 작성해주세요
WITH Q1 AS (
    SELECT '1Q' AS QUARTER, COUNT(*) AS ECOLI_COUNT
    FROM ECOLI_DATA
    WHERE MONTH(DIFFERENTIATION_DATE) BETWEEN 1 AND 3
), Q2 AS (
    SELECT '2Q' AS QUARTER, COUNT(*) AS ECOLI_COUNT
    FROM ECOLI_DATA
    WHERE MONTH(DIFFERENTIATION_DATE) BETWEEN 4 AND 6
), Q3 AS (
    SELECT '3Q' AS QUARTER, COUNT(*) AS ECOLI_COUNT
    FROM ECOLI_DATA
    WHERE MONTH(DIFFERENTIATION_DATE) BETWEEN 7 AND 9
), Q4 AS (
    SELECT '4Q' AS QUARTER, COUNT(*) AS ECOLI_COUNT
    FROM ECOLI_DATA
    WHERE MONTH(DIFFERENTIATION_DATE) BETWEEN 10 AND 12
)

SELECT QUARTER, ECOLI_COUNT FROM Q1
UNION
SELECT QUARTER, ECOLI_COUNT FROM Q2
UNION
SELECT QUARTER, ECOLI_COUNT FROM Q3
UNION
SELECT QUARTER, ECOLI_COUNT FROM Q4