-- 코드를 입력하세요
WITH TEMP AS (
    SELECT H.HISTORY_ID, C.DAILY_FEE, DATEDIFF(H.END_DATE, H.START_DATE) + 1 AS DATE 
    FROM CAR_RENTAL_COMPANY_CAR C
    JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H ON C.CAR_ID = H.CAR_ID
    WHERE C.CAR_TYPE = '트럭'
),
DAY_7 AS (
    SELECT DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN 
    WHERE CAR_TYPE = '트럭' AND DURATION_TYPE = '7일 이상'
),
DAY_30 AS (
    SELECT DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN 
    WHERE CAR_TYPE = '트럭' AND DURATION_TYPE = '30일 이상'
),
DAY_90 AS (
    SELECT DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN 
    WHERE CAR_TYPE = '트럭' AND DURATION_TYPE = '90일 이상'
)

SELECT HISTORY_ID,
    CASE
        WHEN DATE >= 90 THEN ROUND(DAILY_FEE * DATE * (100 - (SELECT DISCOUNT_RATE FROM DAY_90)) / 100)
        WHEN DATE >= 30 THEN ROUND(DAILY_FEE * DATE * (100 - (SELECT DISCOUNT_RATE FROM DAY_30)) / 100)
        WHEN DATE >= 7 THEN ROUND(DAILY_FEE * DATE * (100 - (SELECT DISCOUNT_RATE FROM DAY_7)) / 100)
        ELSE DAILY_FEE * DATE
    END AS FEE
FROM TEMP
ORDER BY FEE DESC, HISTORY_ID DESC