WITH MIN AS (
    SELECT DISTINCT REPLACE(DISCOUNT_RATE, "%", "") AS T
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN 
    WHERE CAR_TYPE = '트럭' AND DURATION_TYPE LIKE '7%'
),
MID AS(
    SELECT DISTINCT REPLACE(DISCOUNT_RATE, "%", "") AS T
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN 
    WHERE CAR_TYPE = '트럭' AND DURATION_TYPE LIKE '30%'
),
MAX AS (
    SELECT DISTINCT REPLACE(DISCOUNT_RATE, "%", "") AS T
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN 
    WHERE CAR_TYPE = '트럭' AND DURATION_TYPE LIKE '90%'
)

SELECT H.HISTORY_ID, 
CASE
    WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 90 
        THEN C.DAILY_FEE * (DATEDIFF(H.END_DATE, H.START_DATE)+1) * (100 - (SELECT T FROM MAX)) / 100
    WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 30 
        THEN C.DAILY_FEE * (DATEDIFF(H.END_DATE, H.START_DATE)+1) * (100 - (SELECT T FROM MID)) / 100
    WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 7 
        THEN C.DAILY_FEE * (DATEDIFF(H.END_DATE, H.START_DATE)+1) * (100 - (SELECT T FROM MIN)) / 100
    ELSE C.DAILY_FEE * (DATEDIFF(H.END_DATE, H.START_DATE)+1)
END AS FEE
FROM CAR_RENTAL_COMPANY_CAR C
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H ON C.CAR_ID = H.CAR_ID
WHERE C.CAR_TYPE = '트럭'
ORDER BY FEE DESC, HISTORY_ID DESC