-- 코드를 입력하세요
WITH TEMP AS (
    SELECT MEMBER_ID, COUNT(*) AS COUNT
    FROM REST_REVIEW 
    GROUP BY MEMBER_ID
),
MAX AS (
    SELECT MAX(COUNT) AS MAX
    FROM TEMP
),
ID AS (
    SELECT MEMBER_ID
    FROM TEMP
    WHERE COUNT = (SELECT MAX FROM MAX)
)

SELECT P.MEMBER_NAME, R.REVIEW_TEXT, DATE_FORMAT(R.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE P
JOIN REST_REVIEW R ON P.MEMBER_ID = R.MEMBER_ID
WHERE P.MEMBER_ID IN (SELECT MEMBER_ID FROM ID)
ORDER BY REVIEW_DATE, R.REVIEW_TEXT