-- 코드를 입력하세요
WITH TEMP AS (
    SELECT COUNT(*) AS C
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
),
MAX_COUNT AS (
    SELECT MAX(C) AS M
    FROM TEMP
), 
MAX_ID AS (
    SELECT MEMBER_ID
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    HAVING COUNT(*) = (SELECT M FROM MAX_COUNT)
)

SELECT P.MEMBER_NAME, R.REVIEW_TEXT, DATE_FORMAT(R.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE P
JOIN REST_REVIEW R ON P.MEMBER_ID = R.MEMBER_ID
WHERE P.MEMBER_ID IN (SELECT MEMBER_ID FROM MAX_ID)
ORDER BY REVIEW_DATE, REVIEW_TEXT               