-- 코드를 작성해주세요
WITH TEMP AS (
    SELECT CODE
    FROM SKILLCODES 
    WHERE NAME IN ('Python', 'C#')
)

SELECT D.ID, D.EMAIL, D.FIRST_NAME, D.LAST_NAME
FROM DEVELOPERS D
JOIN TEMP T ON D.SKILL_CODE & T.CODE = T.CODE
GROUP BY D.ID, D.EMAIL, D.FIRST_NAME, D.LAST_NAME
ORDER BY D.ID