-- 코드를 작성해주세요
WITH TOTAL_SCORE AS (
    SELECT EMP_NO, SUM(SCORE) AS SCORE
    FROM HR_GRADE
    GROUP BY EMP_NO
), 
MAX_SCORE AS (
    SELECT MAX(SCORE) AS MAX_SCORE
    FROM TOTAL_SCORE
),
BSET_PERSON AS (
    SELECT EMP_NO, SCORE
    FROM TOTAL_SCORE
    WHERE SCORE = (SELECT MAX_SCORE FROM MAX_SCORE)
)

SELECT B.SCORE, E.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL
FROM HR_EMPLOYEES E
JOIN BSET_PERSON B ON E.EMP_NO = B.EMP_NO
