-- 코드를 작성해주세요
WITH FRONTEND AS (
    SELECT CODE
    FROM SKILLCODES 
    WHERE CATEGORY = 'FRONT END'
),
PYTHON AS (
    SELECT CODE
    FROM SKILLCODES 
    WHERE NAME = 'Python'
),
CSHARP AS (
    SELECT CODE
    FROM SKILLCODES 
    WHERE NAME = 'C#'
),
A AS (
    SELECT 'A' AS GRADE, D.ID, D.EMAIL
    FROM DEVELOPERS D 
    JOIN FRONTEND F ON D.SKILL_CODE & F.CODE = F.CODE
    JOIN PYTHON P ON D.SKILL_CODE & P.CODE = P.CODE
    GROUP BY D.ID, D.EMAIL
),
B AS (
    SELECT 'B' AS GRADE, D.ID, D.EMAIL
    FROM DEVELOPERS D 
    JOIN CSHARP C ON D.SKILL_CODE & C.CODE = C.CODE
    GROUP BY D.ID, D.EMAIL
),
C AS (
    SELECT 'C' AS GRADE, D.ID, D.EMAIL
    FROM DEVELOPERS D 
    JOIN FRONTEND F ON D.SKILL_CODE & F.CODE = F.CODE
    WHERE D.ID NOT IN (SELECT ID FROM A) AND D.ID NOT IN (SELECT ID FROM B)
    GROUP BY D.ID, D.EMAIL
)

SELECT GRADE, ID, EMAIL FROM A
UNION
SELECT GRADE, ID, EMAIL FROM B
UNION
SELECT GRADE, ID, EMAIL FROM C
ORDER BY GRADE, ID